#!/usr/bin/env python3
"""Generate a device registry by reading the code, never by remembering to update a file.

An earlier version of this plugin told people to hand-maintain `docs/poka-yoke/registry.md`
listing every device and the mistake it prevents. That was rung zero by the plugin's own
argument: a Markdown file someone has to remember to update is training, not a device, and it
goes stale exactly when it matters: the moment someone deletes a "redundant" constraint.

The fix is to keep the rationale where the device is, as a marker comment, and generate the
index from those markers. A generated index cannot drift, because there is nothing to forget.
Delete the constraint and its row disappears; move it and the row follows.

Mark a device at its site, in whatever comment syntax the file uses:

    # poka-yoke: rejects a second charge for the same idempotency key   [control]
    -- poka-yoke: refuses a zero or negative amount                     [control]
    // poka-yoke: forgetting to await this write would lose it silently [warning]

The rung in brackets is optional and defaults to unstated. Then:

    python3 scripts/device_registry.py                    # print the registry
    python3 scripts/device_registry.py --write docs/poka-yoke/registry.md
    python3 scripts/device_registry.py --check            # CI: fail if the file is stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

MARKER = re.compile(
    # A bare "*" prefix was tried and removed: it matches markdown bold (**poka-yoke: ...**),
    # so prose about the plugin was being catalogued as devices. Require a real comment token.
    r"""(?:^|\s)(?:\#|//|--|/\*|<!--)\s*poka-yoke:\s*(?P<what>.+?)\s*(?:\[(?P<rung>control|warning|detection)\])?\s*(?:\*/|-->)?\s*$""",
    re.IGNORECASE,
)

# Generated benchmark transcripts are data, not code, and they discuss the plugin at length.
SKIP = {"results", ".git", "node_modules", "vendor", "dist", "build", "target", "__pycache__",
        ".venv", "venv", ".next", "coverage", ".terraform"}

HEADER = """<!-- Generated by plugins/poka-yoke/scripts/device_registry.py. Do not edit by hand.
     Each row comes from a `poka-yoke:` marker comment at the device itself, so this file
     cannot drift: delete the device and its row disappears. Regenerate with
     `python3 plugins/poka-yoke/scripts/device_registry.py --write docs/poka-yoke/registry.md`. -->

# Device Registry

Every mistake-proofing device in this repository, and the mistake each one prevents. The
"prevents" column is the one that matters: it is what stops a future engineer removing a
device that has never fired because it is doing its job.

| Device | Prevents | Rung |
|---|---|---|
"""


def tracked_files(root: Path) -> list[Path]:
    """Prefer git's file list so ignored files are skipped for free."""
    try:
        r = subprocess.run(["git", "ls-files"], cwd=root, capture_output=True,
                           text=True, timeout=30)
        if r.returncode == 0 and r.stdout.strip():
            return [root / p for p in r.stdout.splitlines()]
    except (subprocess.SubprocessError, FileNotFoundError):
        pass
    return [p for p in root.rglob("*")
            if p.is_file() and not any(s in p.parts for s in SKIP)]


def scan(root: Path) -> list[tuple[str, str, str]]:
    rows = []
    for f in tracked_files(root):
        if any(s in f.parts for s in SKIP):
            continue
        if not f.is_file() or f.suffix in {".png", ".jpg", ".svg", ".pdf", ".lock"}:
            continue
        try:
            text = f.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if "poka-yoke:" not in text:
            continue
        # A marker inside a docstring or a fenced block is documentation showing the
        # syntax, not a device guarding anything. This generator's own module docstring
        # demonstrates three of them, and all three were catalogued as real devices and
        # counted into the badge. A registry that inflates itself by reading its own
        # example is exactly the kind of instrument this repository exists to catch.
        in_doc = False
        for i, line in enumerate(text.splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("```"):
                in_doc = not in_doc
                continue
            if stripped.count('"""') % 2 or stripped.count("'''") % 2:
                in_doc = not in_doc
                continue
            if in_doc:
                continue
            m = MARKER.search(line)
            if m:
                rel = f.relative_to(root)
                rows.append((f"`{rel}:{i}`", m.group("what").strip(),
                             (m.group("rung") or ", ").capitalize()))
    return sorted(rows, key=lambda r: r[0])


def render(rows: list[tuple[str, str, str]]) -> str:
    if not rows:
        return (HEADER + "| _none found_ | Add `poka-yoke:` marker comments at your devices |, |\n")
    return HEADER + "".join(f"| {d} | {w} | {r} |\n" for d, w, r in rows)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--write", metavar="PATH", help="write the registry to PATH")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if --write target is missing or stale (for CI)")
    a = ap.parse_args()

    root = Path(a.root).resolve()
    out = render(scan(root))

    if a.check:
        target = Path(a.write) if a.write else root / "docs/poka-yoke/registry.md"
        if not target.exists():
            print(f"registry missing: {target}", file=sys.stderr); return 1
        if target.read_text() != out:
            print(f"registry is stale: {target}\n"
                  f"regenerate with: --write {target}", file=sys.stderr)
            return 1
        print(f"registry up to date: {target}")
        return 0

    if a.write:
        t = Path(a.write); t.parent.mkdir(parents=True, exist_ok=True)
        t.write_text(out)
        print(f"wrote {t} ({out.count(chr(10)) - HEADER.count(chr(10))} devices)")
    else:
        print(out, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
